name: Delete Provision Roboshop Infrastructure
on: [workflow_dispatch]
jobs:
     DEV-DESTROY:
       runs-on: self-hosted
       steps:
         - uses: actions/checkout@v4
         - name: Terraform Init
           run: terraform init -backend-config=env-dev/state.tfvars
         - name: Terraform destroy
           run: terraform destroy -var-file=env-dev/main.tfvars -auto-approve


     PROD:
        runs-on: self-hosted
        environment: PROD
        needs: DEV-DESTROY
        steps:
          - uses: actions/checkout@4
            name: terraform init
          - run: terraform init -backend-config=env-prod/state.tfvars
          - name: Terraform destroy
            run: terraform destroy -var-file=env-prod/main.tfvars -auto-approve